// MySQL / MariaDB driver (production, Hostinger). The only runtime dependency is `mysql2`.
//
// Conventions shared with the SQLite driver so the services work on both:
//  - `?` placeholders; booleans are stored as 0/1; timestamps are UTC strings generated by the app
//  - db.query(sql, params) -> rows[]      db.run(sql, params) -> { insertId, affectedRows }
//  - db.transaction(async (tx) => ...)    tx has the same query/run methods
export async function openMysql(cfg) {
  const mysql = (await import('mysql2/promise')).default;
  const pool = mysql.createPool({
    host: cfg.host,
    port: cfg.port,
    user: cfg.user,
    password: cfg.password,
    database: cfg.database,
    waitForConnections: true,
    connectionLimit: cfg.poolSize ?? 5,
    charset: 'utf8mb4',
    dateStrings: true, // timestamps come back as plain strings, never shifted by a time zone
    timezone: 'Z',
  });

  const wrap = (conn) => ({
    dialect: 'mysql',
    async query(sql, params = []) {
      const [rows] = await conn.query(sql, params);
      return rows.map((row) => ({ ...row })); // plain objects, same as the SQLite driver
    },
    async run(sql, params = []) {
      const [result] = await conn.query(sql, params);
      return { insertId: result.insertId, affectedRows: result.affectedRows };
    },
  });

  return {
    ...wrap(pool),
    async transaction(fn) {
      const conn = await pool.getConnection();
      try {
        await conn.beginTransaction();
        const result = await fn(wrap(conn));
        await conn.commit();
        return result;
      } catch (err) {
        try {
          await conn.rollback();
        } catch {
          /* the original error is the useful one */
        }
        throw err;
      } finally {
        conn.release();
      }
    },
    async close() {
      await pool.end();
    },
  };
}
